[versions]
jchucomponents = "3.0.0-alpha02"
agp = "9.2.1"
ktor="3.5.1"
kotlin = "2.4.0"
dokka = "2.2.0"
binaryCompatibilityValidator = "0.18.1"
metalava = "1.0.0-alpha14"
androidx-activity = "1.13.0"
androidx-lifecycle = "2.11.0"
androidx-navigation = "2.9.8"
androidx-navigation3 = "1.1.3"
coil-kt = "3.5.0"
org-jetbrains-kotlin = "2.4.0"
org-jetbrains-kotlinx = "1.11.0"
composeBom = "2026.06.00"
desugar_jdk_libs = "2.1.5"

[libraries]
androidx-datastore = "androidx.datastore:datastore-preferences:1.2.1"
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-browser = "androidx.browser:browser:1.10.0"
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = "androidx.compose.material3:material3:1.4.0"
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-core-ktx = "androidx.core:core-ktx:1.19.0"
androidx-core-core-splashscreen = "androidx.core:core-splashscreen:1.2.0"
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-livedata-core-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-preference = "androidx.preference:preference-ktx:1.2.1"
com-google-android-gms-play-services-base = "com.google.android.gms:play-services-base:18.10.0"
com-google-code-gson = "com.google.code.gson:gson:2.14.0"
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil-kt" }
coil-compose-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil-kt" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
revenuecat = "com.revenuecat.purchases:purchases:10.11.0"
compose-bom = { group = "androidx.compose", name ="compose-bom", version.ref = "composeBom" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
metalava = { module = "com.android.tools.metalava:metalava", version.ref = "metalava" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "org-jetbrains-kotlin" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
core-androidx = [
    "androidx-core-core-ktx",
    "androidx-lifecycle-lifecycle-livedata-core-ktx",
    "androidx-lifecycle-lifecycle-viewmodel-ktx",
]
core-jetbrains = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]
# FOR JCHUCOMPONENTS KTX
ktx-androidx = [
    "androidx-browser",
    "androidx-navigation-navigation-compose",
]
ktx-google = [
    "com-google-android-gms-play-services-base",
    "com-google-code-gson",
]

# FOR JCHUCOMPONENTS QR
qr-androidx = [
    "androidx-core-core-ktx"
]
# FOR JCHUCOMPONENTS UI
ui-androidx = [
    "androidx-core-core-splashscreen",
]
compose-bom = [
    "androidx-activity-activity-compose",
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-foundation-foundation-layout",
    "androidx-compose-material",
    "androidx-compose-material-material-icons-extended",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-ui-tooling",
    "androidx-navigation-navigation-compose",
    "coil-compose",
    "coil-compose-ktor"
]
navigation3 = [
    "androidx-navigation3-runtime",
    "androidx-navigation3-ui",
    "androidx-lifecycle-viewmodel-navigation3",
]
# FOR JCHUCOMPONENTS PAY
pay-android = [
    "revenuecat",
]
pay-jetbrains = [
    "org-jetbrains-kotlinx-kotlinx-coroutines-android",
    "org-jetbrains-kotlinx-kotlinx-coroutines-core",
]

# FOR JCHUCOMPONENTS PREFERENCES
preferences-androidx = [
    "androidx-datastore",
    "androidx-preference",
    "androidx-lifecycle-lifecycle-runtime-compose",
]
preferences-google = [
    "com-google-code-gson",
]
preferences-compose = [
    "androidx-compose-runtime",
    "androidx-compose-ui",
]
