package com.jeluchu.composer.core.utils

object DestinationsIds {
    const val back = "back"

    const val buttons = "buttons"
    const val progress = "progress"
    const val surfaces = "surfaces"
    const val text = "text"
    const val chips = "chips"
    const val inputs = "inputs"
    const val layouts = "layouts"
    const val loaders = "loaders"
    const val previews = "previews"
    const val extensions = "extensions"
    const val supabase = "supabase"
    const val room = "room"

    const val floatingButton = "floatingButton"
    const val linearProgress = "linearProgress"
    const val circularProgress = "circularProgress"
    const val iconProgress = "iconProgress"

    const val lazyGrids = "lazyGrids"
    const val lazyStaticGrids = "lazyStaticGrids"

    const val dividers = "dividers"

    const val toolbars = "toolbars"
    const val simpleToolbars = "toolbars"
    const val centerToolbars = "centerToolbars"
    const val largeToolbars = "largeToolbars"

    const val cards = "cards"
    const val benefitCards = "benefitCards"
    const val requirementsCards = "requirementsCards"
    const val assistantCards = "assistantCards"
    const val categoryCards = "categoryCards"
    const val categoryIconCards = "categoryIconCards"
    const val debutCards = "debutCards"
    const val expandableCards = "expandableCards"
    const val infoCards = "infoCards"
    const val teCards = "teCards"
}

object NavigationIds {
    const val buttons = "buttonsNav"
    const val progress = "progressNav"
    const val lazyGrids = "lazyGridsNav"
    const val dividers = "dividersNav"
    const val toolbars = "toolbarsNav"
    const val cards = "cardsNav"
    const val chips = "chipsNav"
    const val inputs = "inputsNav"
    const val loaders = "loadersNav"
    const val previews = "previewsNav"
    const val extensions = "extensionsNav"
}

object Names {
    const val buttons = "Buttons"
    const val progress = "Progress"
    const val surfaces = "Surfaces"
    const val text = "Text"
    const val chips = "Chips"
    const val inputs = "Inputs"
    const val layouts = "Layouts"
    const val loaders = "Loaders"
    const val previews = "Previews"
    const val extensions = "Extensions"
    const val supabase = "Supabase Lab"
    const val room = "Room 3 Lab"
    const val floatingButtons = "FloatingButtons"
    const val linearProgress = "LinearProgress"
    const val circularProgress = "CircularProgress"
    const val iconProgress = "IconProgress"
    const val lazyGrids = "LazyGrids"
    const val lazyStaticGrids = "LazyStaticGrids"
    const val dividers = "Dividers"
    const val toolbars = "Toolbars"
    const val centerToolbars = "CenterToolbars"
    const val largeToolbars = "LargeToolbars"
    const val cards = "Cards"
    const val benefitCards = "BenefitCards"
    const val requirementsCards = "RequirementsCards"
    const val assistantCards = "AssistantCards"
    const val categoryCards = "CategoryCards"
    const val categoryIconCards = "CategoryIconCards"
    const val debutCards = "DebutCards"
    const val expandableCards = "ExpandableCards"
    const val infoCards = "InfoCards"
    const val teCards = "TeCards"
}
